MODEL:
  VISUAL:
    NAME: "RN50"
  LANG:
    NAME: "clip"

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"

DATALOADER:
  TRAIN:
    BATCH_SIZE: 64
    SHUFFLE: True
  TEST:
    BATCH_SIZE: 64
    SHUFFLE: False
  VAL:
    BATCH_SIZE: 64
    SHUFFLE: False
  NUM_WORKERS: 4